graph TD
    compute/consistent-->compute/component-ci-testing-->compute/promoted-components-->promoted-components
    cinder/consistent-->cinder/component-ci-testing-->cinder/promoted-components-->promoted-components
    security/consistent-->security/component-ci-testing-->security/promoted-components-->promoted-components
    promoted-components-->tripleo-ci-testing-->current-tripleo
