graph TD
    master --> |build-packages|current-consistent
    current-consistent --> |<a href='http://cistatus.tripleo.org/promotion/'>tripleo-ci promotion</a>|current-tripleo
    current-tripleo --> |<a href='http://cistatus.tripleo.org/phase1/'>rdo phase1 promotion</a>|current-tripleo-rdo
    current-tripleo-rdo --> |<a href='http://cistatus.tripleo.org/phase2/'>rdo phase2 promotion</a>|current-tripleo-rdo-internal
