# instack-undercloud documentation build configuration file, created by
# sphinx-quickstart on Wed Feb 25 10:56:57 2015.
#
# This file is execfile()d with the current directory set to its containing
# dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# import os
# import sys

from pyquery import PyQuery
import requests

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.mermaid',
    'openstackdocstheme',
    'sphinxcontrib.rsvgconverter',
]

# Disable usage of xindy https://bugzilla.redhat.com/show_bug.cgi?id=1643664
latex_use_xindy = False


# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'TripleO'
copyright = u'2015, OpenStack Foundation'
bug_tracker = u'Launchpad'
bug_tracker_url = u'https://launchpad.net/tripleo'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '3.0.0'
# The full version, including alpha/beta/rc tags.
# release = '3.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []


# -- Options for HTML output -------------------------------------------------

html_static_path = ['../../_custom']
# html_style = 'custom.css'
templates_path = ['../../_templates']

# Output file base name for HTML help builder.
htmlhelp_basename = '%sdoc' % project

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'openstackdocs'

# -- Options for LaTeX output ------------------------------------------------


def _get_name_version(index=1):
    response = requests.get('https://releases.openstack.org/')
    release_list = PyQuery(response.content)
    all_tr = release_list('tr')
    release = all_tr('td:first')[index]

    return release.text_content()


def get_oldest_version_name():
    return _get_name_version(index=4)


def get_before_oldest_version_name():
    return _get_name_version(index=3)


def get_before_latest_version_name():
    return _get_name_version(index=2)


def get_latest_version_name():
    """Get the name of the last stable version"""
    return _get_name_version()


# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto/manual]).
latex_documents = [
    ('index',
     'doc-tripleo-docs.tex',
     u'TripleO Documentation',
     u'OpenStack Foundation', 'manual'),
]

# Allow deeper levels of nesting for \begin...\end stanzas
latex_elements = {'maxlistdepth': 10, 'extraclassoptions': 'openany,oneside'}

oldest_version_name = get_oldest_version_name()
oldest_version_name_lower = oldest_version_name.lower()
before_oldest_version_name = get_before_oldest_version_name()
before_oldest_version_name_lower = before_oldest_version_name.lower()
before_latest_version_name = get_before_latest_version_name()
before_latest_version_name_lower = before_latest_version_name.lower()
latest_version_name = get_latest_version_name()
latest_version_name_lower = latest_version_name.lower()
rst_prolog = """
.. |project| replace:: {project}
.. |bug_tracker| replace:: {bug_tracker}
.. |bug_tracker_url| replace:: {bug_tracker_url}
.. |oldest_version_name| replace:: {oldest_version_name}
.. |oldest_version_name_lower| replace:: {oldest_version_name_lower}
.. |before_oldest_version_name| replace:: {before_oldest_version_name}
.. |before_oldest_version_name_lower| replace:: {b_oldest_version_name_lower}
.. |before_latest_version_name| replace:: {before_latest_version_name}
.. |before_latest_version_name_lower| replace:: {b_latest_version_name_lower}
.. |latest_version_name| replace:: {latest_version_name}
.. |latest_version_name_lower| replace:: {latest_version_name_lower}
""".format(
    project=project, bug_tracker=bug_tracker, bug_tracker_url=bug_tracker_url,
    oldest_version_name=oldest_version_name,
    oldest_version_name_lower=oldest_version_name_lower,
    before_oldest_version_name=before_oldest_version_name,
    b_oldest_version_name_lower=before_oldest_version_name_lower,
    before_latest_version_name=before_latest_version_name,
    b_latest_version_name_lower=before_latest_version_name_lower,
    latest_version_name=latest_version_name,
    latest_version_name_lower=latest_version_name_lower
)

# openstackdocstheme options
repository_name = 'openstack/tripleo-docs'
bug_project = 'tripleo'
bug_tag = 'documentation'
